### ISSUE TITLE
DlaOptions not found

### ISSUE THREAD

**Issue by Sil911** [BobLd/camelot-sharp#3]
I tried to used example from Readme, but got stuck
Cannot find DlaOptions type in a package. In PdfPig it's not presented as well
![image](https://user-images.githubusercontent.com/27447947/198135723-17cfbcb1-52ee-4445-9c37-b1c648923194.png)

**Comment by George-Vlad** [comment]
Use pdf ping version 0.1.5-alpha001 and it will work

**Comment by BobLd** [comment]
I need to release a new package with the latest PdfPig version

**Comment by jonathandlo** [comment]
Hi, I am facing the same issue. Is the latest version available on NuGet?
Using 0.0.1 alpha 2 camelot sharp, and 1.11 alpha pdfpig
